### ISSUE TITLE
hidapitester --vidpid 5131:2007 --open --send-output 0xA0,01,01,A2 --close

### ISSUE THREAD

**Issue by wlan4you** [alfem/usb-relay-control#1]
Hello,

i see you have absolutly the same module like me.
I also read that you tryed to bring them work under windows.

hidapitester --vidpid 5131:2007 --open --send-output 0xA0,01,01,A2 --close

I need also an easy solution to run it under windows like a batch file.

You find more? or a solution without to use python?

With the original tool i find out which is goning on and off.
I put it into a excel sheet.

![Excel](https://github.com/alfem/usb-relay-control/assets/60288714/693b7e4c-4a5a-440f-b8e4-63c44ad39c49)
![Micro USB 1_2_4 Kanal HID Relais Modul](https://github.com/alfem/usb-relay-control/assets/60288714/f79219fa-8561-4311-9366-aa7f633c2f3c)
![OrigTestTool](https://github.com/alfem/usb-relay-control/assets/60288714/f57301f1-c987-40d8-a8c4-7cdad1133578)
![Output](https://github.com/alfem/usb-relay-control/assets/60288714/541f114f-af9c-4021-8e1c-9d3c14aa7967)

This has i found on a webpage.
It has the same information what i found out with my test.
But it will not going with a batch file

Protocolo de interruptor USB LC:

Datos (1) --- identidad inicial (el valor predeterminado es 0xA0)
Datos (2) --- Código de Dirección del interruptor (el valor predeterminado es 0x01, identificando el interruptor del primer canal)
Datos (3) --- Datos operativos (0x00 a "Off", 0x01 "On")
Datos (4) --- suma de comprobación

Ejemplo:
Interruptor USB abierto: A0 01 01 A2
Cerrar interruptor USB: A0 01 00 A1

**Comment by alfem** [comment]
I do not use windows, and I finally switched to another solution (arduino board + relay shield) because I needed feedback from some sensors (and relay control as well). 

But I guess you can do something like:
```

echo A00101A2 > command.txt
certutil -decodehex command.txt command.bin

MODE COM8:115200,n,8,1
copy command.bin \\.\com1 /b
```

**Comment by wlan4you** [comment]
These module use no comport.
It is the same module what you have used here:

https://github.com/darrylb123/usbrelay/issues/103

**Comment by alfem** [comment]
Yes, it is the same. USB is a com port

**Comment by wlan4you** [comment]
Hmmm.... if i type MODE COM8....
Then comes error that com port

Illegal device name - COM8
Nombre de dispositivo ilegal - COM8

If i take a look in my Win11 when the relay is connected. there is no COMPORT.
Only the HID Device

**Comment by alfem** [comment]
COM8 is only an example. In your computer It could be COM1, COM2...

Check Windows Device Manager.

**Comment by wlan4you** [comment]
There is no COM, if i connected them to windows.
It is a HID Device.
They have no COM.

You have not the same module ?

**Comment by alfem** [comment]
Perhaps you don't have the USB drivers for CH340 installed. It is included in Linux, but not in Windows. 

You can find that drivers in many web pages:

https://learn.sparkfun.com/tutorials/how-to-install-ch340-drivers/all

**Comment by wlan4you** [comment]
On my Module is no CH340
I have a CH554E installed

**Comment by alfem** [comment]
` I have a CH554E installed`

And you have the proper windows drivers installed?

**Comment by wlan4you** [comment]
They don't need a driver.
They can talk as a HID device.

OK.
Close it here.
I have first uinderstand you have the same RELAY MOdule like me.
See Screenshot from first post.

Here are sam Macro PICS from the chip.
![IMG_9002](https://github.com/alfem/usb-relay-control/assets/60288714/847e4b0b-d3c7-4fd3-85c0-9533cc83d4f7)
![IMG_8999](https://github.com/alfem/usb-relay-control/assets/60288714/0eb8e8c3-6177-4857-b212-fbc222300497)
![IMG_8998](https://github.com/alfem/usb-relay-control/assets/60288714/a5fc6ebf-2e1c-4ae6-baae-9e0e1ae03303)


Thanks for your help to try and your time.

**Comment by mpfdetroit** [comment]
@wlan4you I also have the HID version of this piece of shit.  Did you end up finding a solution to make it work with a bat file?  

I tried using hidapitester to send output, but the relay did not actuate.  Have you found a way to actuate it using the hidapitester? Or have you found a solution?

**Comment by mpfdetroit** [comment]
![image](https://github.com/alfem/usb-relay-control/assets/159389907/6a513efe-e3c6-40b5-90e6-80f851204947)

**Comment by mpfdetroit** [comment]
also, program is not writing?

**Comment by mpfdetroit** [comment]
@alfem Do you think you could point me in the right direction?  Similar to @wlan4you I have the HID-type relay.  I'm think though they use the same integrated circuits as the ch340's the configuration inside the USB protocol is different.  But I have no clue how to get this thing to work, all I know is that it can work under windows because it came with the lc_usb.exe that actuates the relay.  

I've tried to wireshark the usb to some success, but I don't have to knowledge to send the same data to the relay that the .exe file is sending.

**Comment by wlan4you** [comment]
Hello,
NO
i didn't find a solution with this piece of shit (LOL).
I search hours in the web.
I testet a lot of... nobody has this module running over a batch file.

Please if you find a way, write to me or here in this part here.
THANKS !

**Comment by maciejbudzyn** [comment]
.\hidapitester.exe --vidpid 5131:2007 --open --send-output 0x0,0xA0,0x01,0x01,0xA2 --close 

works

**Comment by wlan4you** [comment]
> .\hidapitester.exe --vidpid 5131:2007 --open --send-output 0x0,0xA0,0x01,0x01,0xA2 --close
> 
> works

Jaaabbbaaaddaaaabbbaaadddduuuuuuuuu !!!
It goes !
Your the best.
I was on the way, but i didn't now about the "Ax" before

Great. Many Thanks

**Comment by mpfdetroit** [comment]
It works! You are the man.  Thank you so much.

**Comment by onur-akaydin** [comment]
> .\hidapitester.exe --vidpid 5131:2007 --open --send-output 0x0,0xA0,0x01,0x01,0xA2 --close
> 
> works

It works on Windows! I would never have thought of adding an extra 0x0 at the beginning. Thanks!
