### ISSUE TITLE
Relay control is reversed

### ISSUE THREAD

**Issue by wkazubski** [alfem/usb-relay-control#2]
According to documentation, sending "1" to the module should switch the relay on and sending "0:" should switch it off.. This can be confirmed, the relay LED shoul light up when the relay is active (on) or by checking the volage across the relay coil. However the script sends "0" when is called with "on" argumet and "1" when called with "off", so the operation is reversed.

**Comment by alfem** [comment]
It the seller's page I can read:

_Open USB switch: A0 01 01 A2
Close USB switch: A0 01 **00** A1_

For me, a 'closed switch" is a relay allowing current go thru its contacts. So a light, motor, etc would be "on".

Anyway, I will check the indicator LED to make everything coherent.

**Comment by wkazubski** [comment]
The manfacturers webpage http://www.chinalctech.com/cpzx/Programmer/Relay_Module/131.html contins this:

_LC USB switch the default communication baud rate: 9600 BPS

LC USB switch communication protocol

Data (1) - startup logo (the default is 0 xA0)

Data (2) - switch address code (the default is 0 x01, identifies the first switch)  

Data (3) - operation data (0 x00 to "off", 0 x01 to "on")

Data (4) - check code_

and the above example. The relay is SPDT so switching off (with 0) closes circuit between COM and NC contacts and switching on opens CON and NC but closes COM and NO.

**Comment by alfem** [comment]
Ok. I changed the code.

Thanks for the info!
